name: priorise
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_secure_storage: ^9.2.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  google_fonts: ^6.2.1
  get_it: ^7.7.0
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0
  timezone: ^0.9.2
  flutter_timezone: ^5.1.0
  autostart_settings: ^0.2.0
  flutter_local_notifications: ^17.1.2
  dio: ^5.4.0
  home_widget: ^0.9.3
  flutter_gen: ^5.9.0
  path_provider: ^2.1.6
  flutter_native_splash: ^2.4.8
  package_info_plus: ^9.0.1

dev_dependencies:
  build_runner: ^2.4.6
  isar_generator: ^3.1.0+1
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/priorise-icon-512.png"
  adaptive_icon_background: "assets/icons/priorise-icon-adaptive-background-512.png"
  adaptive_icon_foreground: "assets/icons/priorise-icon-adaptive-foreground-512.png"

flutter_native_splash:
  color: "#F8F4E9"
  color_dark: "#1B140B"

  android_12:
    color: "#F8F4E9"
    color_dark: "#1B140B"
